# Generated by Django 2.2.3 on 2019-11-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_cab_details_hospital_details_hotel_details_medical_details_package_details_petrol_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('starttime', models.CharField(max_length=30)),
                ('endtime', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='location',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='place',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='starttime',
        ),
    ]
