# Generated by Django 2.2.3 on 2019-11-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20191111_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_details',
            name='pacakge_id',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
