# Generated by Django 2.2.3 on 2019-11-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_place_details_pacakge_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='railway_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cab_details',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hospital_details',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel_details',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medical_details',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='petrol_details',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place_details',
            name='location',
            field=models.TextField(),
        ),
    ]
