# Generated by Django 2.2.3 on 2019-11-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20191112_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cab_details',
            old_name='cabname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hospital_details',
            old_name='hospitalname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotel_details',
            old_name='hotelname',
            new_name='name',
        ),
    ]
