# Generated by Django 2.2.3 on 2019-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_cab_booking_hotel_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab_booking',
            name='cab_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='hotel_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
