# Generated by Django 2.2.3 on 2019-12-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20191119_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_ref', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
                ('review', models.TextField()),
            ],
        ),
    ]
