# Generated by Django 2.2.3 on 2019-12-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_rating_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='cab_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('cab_ref', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
                ('review', models.TextField()),
            ],
        ),
    ]
