# Generated by Django 2.2.3 on 2020-01-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_cab_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
                ('review', models.TextField()),
            ],
        ),
    ]
