# Generated by Django 2.2.7 on 2020-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_app_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place_details',
            old_name='endtime',
            new_name='kilometer_extra',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='breakfasttime',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='dinnertime',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='lunchtime',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='teatime',
        ),
        migrations.RemoveField(
            model_name='place_details',
            name='starttime',
        ),
        migrations.AddField(
            model_name='package_details',
            name='kilometers',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
