# Generated by Django 2.2.7 on 2020-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20200129_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_details',
            name='kilometer_extra',
        ),
        migrations.AddField(
            model_name='place_details',
            name='kilometers',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
