# Generated by Django 3.2.3 on 2021-09-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_place_details_kilometers_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='package_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=30)),
                ('comment', models.TextField()),
            ],
        ),
    ]
