# Generated by Django 3.2.3 on 2021-09-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_package_booking_package_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to='blog/')),
                ('comment', models.TextField()),
            ],
        ),
    ]
