# Generated by Django 3.2.3 on 2021-10-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='pic',
            field=models.ImageField(upload_to='blogs/'),
        ),
    ]
