# Generated by Django 3.2.3 on 2021-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_auto_20211010_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='store_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
