# Generated by Django 3.2.9 on 2021-11-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_coupon_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='place',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
