# Generated by Django 3.2.9 on 2021-11-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_auto_20211110_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
