# Generated by Django 3.2.9 on 2021-11-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_blog_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medical_details',
            new_name='hot_spots',
        ),
    ]
